services:
  - type: web
    name: backend-ong
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "composer install --no-dev --optimize-autoloader && php artisan config:clear"
    startCommand: "php artisan serve --host=0.0.0.0 --port=80"
